# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ab2a9fdcdabc69f52d5e90ef08b23c02d01ed4095ddaecc645e9e29e4998b9849dfd893014e3f960bffd22d0b025eb72f26f18fbffc73b373e0274dde7a8e2

test:
  secret_key_base: 60c0c7beb533c5ed2080c0fbbb7c50f03fbabb0a617bb29f7e1ca5c0dd9293fbe8ecb5460f5daff6260f3d81f7bd44520d47a7f93993d5e606fa31f2a52cd951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
